### ISSUE TITLE
Segmentation violation when exiting program

### ISSUE THREAD

**Issue by semrekkers** [brettbuddin/shaden#6]
I sometimes get a `SIGSEGV` when exiting Shaden. Stacktrace:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x7f38fad662f9]

runtime stack:
runtime.throw(0x890aa4, 0x2a)
        /usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:351 +0x2b8

goroutine 22 [syscall, locked to thread]:
runtime.cgocall(0x79af40, 0xc420218e48, 0x890098)
        /usr/local/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc420218e08 sp=0xc420218dc8 pc=0x404b94
buddin.us/shaden/vendor/github.com/rakyll/portmidi._Cfunc_Pm_Read(0x1e96bc0, 0xc42055e000, 0x400, 0x0)
        buddin.us/shaden/vendor/github.com/rakyll/portmidi/_obj/_cgo_gotypes.go:249 +0x4d fp=0xc420218e48 sp=0xc420218e08 pc=0x76483d
buddin.us/shaden/vendor/github.com/rakyll/portmidi.(*Stream).Read.func1(0x1e96bc0, 0xc42055e000, 0x400, 0xc42055e000)
        /home/sem/go/src/buddin.us/shaden/vendor/github.com/rakyll/portmidi/stream.go:169 +0x72 fp=0xc420218e80 sp=0xc420218e48 pc=0x7663a2
buddin.us/shaden/vendor/github.com/rakyll/portmidi.(*Stream).Read(0xc4201608b0, 0x400, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sem/go/src/buddin.us/shaden/vendor/github.com/rakyll/portmidi/stream.go:169 +0x93 fp=0xc420218ed8 sp=0xc420218e80 pc=0x765983
buddin.us/shaden/midi.eventStream.func1(0xc4201608b0, 0xc4201461e0, 0xc420146240)
        /home/sem/go/src/buddin.us/shaden/midi/midi.go:74 +0x12c fp=0xc420218fc8 sp=0xc420218ed8 pc=0x76ab4c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420218fd0 sp=0xc420218fc8 pc=0x45f951
created by buddin.us/shaden/midi.eventStream
        /home/sem/go/src/buddin.us/shaden/midi/midi.go:63 +0x71

goroutine 1 [panicwait]:
runtime.gopark(0x0, 0x0, 0x881074, 0x9, 0x10, 0x1)
        /usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.main()
        /usr/local/go/src/runtime/proc.go:214 +0x2b1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0xca7b80)
        /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [select, 1 minutes, locked to thread]:
runtime.gopark(0x89b448, 0x0, 0x87ec2e, 0x6, 0x18, 0x1)
        /usr/local/go/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420046f50, 0xc42001e540)
        /usr/local/go/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1

goroutine 18 [IO wait]:
internal/poll.runtime_pollWait(0x7f38fb52df70, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420144098, 0x72, 0xc420040c00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420144098, 0xffffffffffffff00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420144080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420144080, 0x89b560, 0xc420040d90, 0x4046cb)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42013c018, 0x7f9380, 0xc420040dc0, 0x403467)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42013c018, 0xc420040e08, 0xc420040e10, 0xc420040e00)
        /usr/local/go/src/net/tcpsock.go:234 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42013c018, 0x89ae68, 0xc420090140, 0xca91c0, 0xc420130330)
        /usr/local/go/src/net/http/server.go:3120 +0x2f
net/http.(*Server).Serve(0xc4201c4000, 0xca8b80, 0xc42013c018, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2695 +0x1b2
net/http.(*Server).ListenAndServe(0xc4201c4000, 0xc4201c4000, 0x5)
        /usr/local/go/src/net/http/server.go:2636 +0xa9
net/http.ListenAndServe(0x87d486, 0x5, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2882 +0x7f
main.serve(0x87d486, 0x5, 0xc4201485a0, 0x0, 0x0)
        /home/sem/go/src/buddin.us/shaden/main.go:207 +0xa1
main.run.func3(0xc4201602a0, 0xc4201485a0, 0xc4201640f0)
        /home/sem/go/src/buddin.us/shaden/main.go:128 +0x45
created by main.run
        /home/sem/go/src/buddin.us/shaden/main.go:127 +0x80f
```

**OS:** Ubuntu 17.10 x86_64
**Go:** go version go1.9.2 linux/amd64
**Shaden:** a2579309d19e25da4f4d152b9cc65b45e0c162be

**Comment by brettbuddin** [comment]
I've identified the cause. I'll have a patch for you tonight.

**Comment by brettbuddin** [comment]
It seems that I had overlooked invoking `Close()` on Units when they are removed from the graph and when the engine is shut down or reset. I've added that behavior in and ensured that the MIDI stream consumers are shut down appropriately. Here are the changes I've made:

https://github.com/brettbuddin/shaden/compare/34851bd8868225d2f13a05c7210c119079cbdadc...master

Could you give these a spin?

**Comment by semrekkers** [comment]
Seems that it's solved, thanks!
